#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

set -e

if [ ! -d "${OPENSHIFT_DATA_DIR}/public" ]; then
  mkdir "${OPENSHIFT_DATA_DIR}/public"
fi

# Allow write access for next step.
chmod u+w ${OPENSHIFT_REPO_DIR}/sites/default

cd "${OPENSHIFT_REPO_DIR}/sites/default"
ln -s ../../../data/public files

cd "${OPENSHIFT_REPO_DIR}"
vendor/bin/drush cc drush
vendor/bin/drush @prod updatedb -y
vendor/bin/drush @prod cc all

# Prevent write access for security.
chmod u-w ${OPENSHIFT_REPO_DIR}/sites/default
chmod u-w ${OPENSHIFT_REPO_DIR}/sites/default/settings.php