<?php

/**
 * @file
 * Hook implementations for the aldes_system module.
 */

use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_entity_field_access().
 *
 * Access to all custom fields on the user object is denied unless the user has
 * the permission 'manage membership information'.
 */
function aldes_system_entity_field_access($operation, \Drupal\Core\Field\FieldDefinitionInterface $field_definition, \Drupal\Core\Session\AccountInterface $account, \Drupal\Core\Field\FieldItemListInterface $items = NULL) {
  $entity_type = $field_definition->getTargetEntityTypeId();

  if ($entity_type === 'user') {
    return AccessResult::forbiddenIf(!$account->hasPermission('manage membership information'));
  }

  return AccessResult::neutral();
}
